# Generated by Django 3.2 on 2022-07-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-id',)},
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='calender',
            new_name='calendar',
        ),
    ]
