# Generated by Django 3.2 on 2022-07-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20220715_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
