# Generated by Django 3.2 on 2022-07-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20220727_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='status',
        ),
        migrations.CreateModel(
            name='CourseRegistrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courseRegistrationStatus', to='operations.session')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseRegistrationStatus', to='operations.student')),
            ],
        ),
    ]
