# Generated by Django 3.2 on 2022-07-27 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20220727_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistrationstatus',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courseregistrationstatus', to='operations.session'),
        ),
        migrations.AlterField(
            model_name='courseregistrationstatus',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseregistrationstatus', to='operations.student'),
        ),
    ]
