# Generated by Django 3.2 on 2022-07-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20220727_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date_created',
        ),
    ]
