# Generated by Django 3.2 on 2022-07-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_remove_payment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='name',
            field=models.CharField(choices=[('tuition', 'tuition'), ('acceptance', 'acceptance')], max_length=255),
        ),
    ]
