# Generated by Django 3.2 on 2022-09-03 12:25

from django.db import migrations, models
import operations.models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20220903_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='secondary_cert',
            field=models.FileField(blank=True, null=True, upload_to=operations.models.applicant_secondary_cert_location),
        ),
        migrations.AddField(
            model_name='applicant',
            name='testimonial',
            field=models.FileField(blank=True, null=True, upload_to=operations.models.applicant_testimonial_location),
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_cert',
            field=models.FileField(blank=True, null=True, upload_to=operations.models.applicant_secondary_cert_location),
        ),
        migrations.AddField(
            model_name='student',
            name='testimonial',
            field=models.FileField(blank=True, null=True, upload_to=operations.models.applicant_testimonial_location),
        ),
    ]
