# Generated by Django 3.2 on 2022-09-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20220903_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
