# Generated by Django 3.2 on 2022-09-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_auto_20220903_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
    ]
