# Generated by Django 3.2 on 2022-09-03 23:08

from django.db import migrations, models
import operations.models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=operations.models.staff_image_location),
        ),
    ]
